<?php
/**
 * ConsentKit tracker database — GENERATED FILE, DO NOT EDIT.
 *
 * Generated by tools/export-hostdb.mjs from src/ck-core.js of the ConsentKit
 * client (version 0.3.6). The client is the single source of truth: edit
 * HOST_DB / PATH_DB there and re-run
 *
 *     node tools/export-hostdb.mjs
 *
 * test/hostdb.test.mjs fails when this file drifts from the client, so a stale
 * copy cannot ship: the server-side markup would then classify a host
 * differently from the browser engine that runs on the very same page.
 *
 * "hosts" is matched by suffix (host === key, or host ends with "." . key),
 * "paths" by case-insensitive substring against the whole URL — exactly what
 * categoryForUrl() does in ck-core.js.
 *
 * This file intentionally carries no ABSPATH guard and no side effects: it is
 * pure data loaded with require(), including by the PHP CLI test that runs
 * without WordPress.
 *
 * @package ConsentKit
 */

return array(
	'hosts' => array(
		'adroll.com' => 'marketing',
		'ads-twitter.com' => 'marketing',
		'ads.linkedin.com' => 'marketing',
		'amazon-adsystem.com' => 'marketing',
		'amplitude.com' => 'analytics',
		'analytics.google.com' => 'analytics',
		'analytics.tiktok.com' => 'marketing',
		'bat.bing.com' => 'marketing',
		'chimpstatic.com' => 'marketing',
		'clarity.ms' => 'analytics',
		'connect.facebook.net' => 'marketing',
		'crazyegg.com' => 'analytics',
		'crisp.chat' => 'functional',
		'criteo.com' => 'marketing',
		'criteo.net' => 'marketing',
		'ct.pinterest.com' => 'marketing',
		'datadoghq-browser-agent.com' => 'analytics',
		'datadoghq.com' => 'analytics',
		'doubleclick.net' => 'marketing',
		'drift.com' => 'functional',
		'driftt.com' => 'functional',
		'facebook.net' => 'marketing',
		'fullstory.com' => 'analytics',
		'google-analytics.com' => 'analytics',
		'googleadservices.com' => 'marketing',
		'googlesyndication.com' => 'marketing',
		'heap.io' => 'analytics',
		'heapanalytics.com' => 'analytics',
		'hotjar.com' => 'analytics',
		'hotjar.io' => 'analytics',
		'hs-analytics.net' => 'marketing',
		'hs-scripts.com' => 'marketing',
		'hsadspixel.net' => 'marketing',
		'intercom.io' => 'functional',
		'intercomcdn.com' => 'functional',
		'jivo.chat' => 'functional',
		'jivosite.com' => 'functional',
		'list-manage.com' => 'marketing',
		'livechatinc.com' => 'functional',
		'logrocket.com' => 'analytics',
		'lr-ingest.io' => 'analytics',
		'matomo.cloud' => 'analytics',
		'mc.yandex.com' => 'analytics',
		'mc.yandex.ru' => 'analytics',
		'mixpanel.com' => 'analytics',
		'mouseflow.com' => 'analytics',
		'mxpnl.com' => 'analytics',
		'newrelic.com' => 'analytics',
		'nr-data.net' => 'analytics',
		'outbrain.com' => 'marketing',
		'plausible.io' => 'analytics',
		'q.quora.com' => 'marketing',
		'redditstatic.com' => 'marketing',
		'sc-static.net' => 'marketing',
		'segment.com' => 'analytics',
		'segment.io' => 'analytics',
		'smartlook.cloud' => 'analytics',
		'smartlook.com' => 'analytics',
		'snap.licdn.com' => 'marketing',
		'ssl.google-analytics.com' => 'analytics',
		'static.ads-twitter.com' => 'marketing',
		'taboola.com' => 'marketing',
		'tawk.to' => 'functional',
		'tidio.co' => 'functional',
		'tidiochat.com' => 'functional',
		'zdassets.com' => 'functional',
		'zopim.com' => 'functional',
	),
	'paths' => array(
		'/gtag/js' => 'analytics',
		'/trackers/chat.js' => 'functional',
		'/trackers/ga.js' => 'analytics',
		'/trackers/pixel.js' => 'marketing',
	),
);
